### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by appleimperio** [jordan1982/temperaturino#1]
I am a completely noob. Im trying to compile this in arduino but getting compiling error like BME680CONFIG.h no such file or directory. This looks really promising even with the printable enclosure. Thanks

**Comment by jordan1982** [comment]
Hi,
sorry for the delay in replying.
I forgot to add a copy of the "BME680Config" and "WiFiManagerConfig" libraries to the guide. You have to download the two folders contained under "lib" of github and copy them into your arduino library folder. For example "E: \ mypath \ Arduino \ libraries \".
Let me know if you are able to compile in successfully.

**Comment by appleimperio** [comment]
Thanks for your help. I add the folders to this path. Now im gettin this error 
In file included from /Users/Documents/Arduino/temperaturino/temperaturino.ino:2:0:
/Users/Documents/Arduino/libraries/WIFIMANAGERCONFIG/WIFIMANAGERCONFIG.h:5:26: fatal error: WiFiManager.h: No such file or directory
compilation terminated.
exit status 1
Error compiling for board ESP32 Dev Module.

and its there.

![Screen Shot 2021-02-17 at 4 01 26 PM](https://user-images.githubusercontent.com/72883739/108267628-73836e80-7139-11eb-8b28-fe335319e456.png)

**Comment by jordan1982** [comment]
You must install wifimanager library.
https://github.com/tzapu/WiFiManager
Let me know, thank you

**Comment by appleimperio** [comment]
got it just add #define LED_BUILTIN 13 to the BME680CONFIG.cpp. and you need to update the password in the readme is temperature2021. Thank you very much great work!

**Comment by jordan1982** [comment]
Hi, thanks for the further info, I will add them to the project readme. Let me know how you feel with the sensor firmware, I am a beginner with arduino and any feedback is welcome.
